name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
  push:
    tags:
      - "*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      # Install Rust
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      # Install build dependencies
      - name: Install dependencies
        run: |
          cargo install --git https://github.com/TheBevyFlock/bevy_cli --tag cli-v0.1.0-alpha.1 --locked bevy_cli
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli
          cargo install wasm-opt

      # Build with trunk from web_frontend directory
      - name: Build and run
        run: |
          bevy build --release web --bundle

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "target/bevy_web/web-release/world_line"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Install butler for deploying to itch
      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      # Uploads to itch.io
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          for channel in $(ls builds); do
            if [ "$channel" = "github-pages" ]; then
              continue
            fi
            ./butler push \
              --fix-permissions \
              --userversion="${{ inputs.tag }}" \
              builds/$channel/* \
              ${{ dresio/world-line }}:$channel
          done
